language: node_js

node_js : 
    - "0.10"
    - "0.11"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcv-dev libopencv-dev libhighgui-dev libjpeg-dev libpng-dev libwebp-dev libtiff-dev